name: Extract Source Code

on:
  push:
    paths:
      - 'hex/**'  # Specify the path to your YAML file
  workflow_dispatch:

jobs:
  extract_source_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Extract Source Code
        run: python extract_source_code.py

      - name: Save Source Code to Unique File
        id: save_source_code
        run: |
          python extract_source_code.py
          output_dir=""
          saved_file_path=$(python extract_source_code.py ${{ github.workspace }}/hex/mlops.yaml $output_dir)
          echo "$steps.save_source_code.outputs.saved_file_path"
          
        
      - name: Commit and Push Changes
        run: |
          git config --local user.email "manthan.kumar@progressresidential.com"
          git config --local user.name "manthankumar12"
          cd ${{ github.workspace }} # Change directory to where the file is saved
          git add .
          git commit -m "Extracted source code from YAML"
          git push
