name: Extract Source Code

on:
  push:
    paths:
      - 'hex/**'  # Specify the path to your YAML file
  workflow_dispatch:

jobs:
  extract_source_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Extract Source Code
        run: |
          python extract_source_code.py
          git add output.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "manthan.kumar@progressresidential.com"
          git config --local user.name "manthankumar12"
          git commit -m "Extracted source code from YAML"
          git push
