on:
  push:
    paths:
      - 'hex/**'
  workflow_dispatch:
 
jobs:
  extract_and_convert:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Grant execute permissions to the script
        run: chmod +x hex/extract_source_code.sh

      - name: Extract source code from YAML
        run: ./hex/extract_source_code.sh
        
      - name: Grant execute permissions to the script
        run: chmod +x hex/create_python_file.sh
      
      - name: Create Python File
        run: ./hex/create_python_file.sh

      - name: Configure Git
        run: |
          git config --local user.email "manthan.kumar@progressresidential.com"
          git config --local user.name "manthankumar12"
          git remote set-url origin "https://manthankumar12:${GH_PAT}@github.com/manthankumar12/mlops_demo.git"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto-generated Python file"
          git push
