name: Deploy Python File to Snowflake

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  deploy_to_snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Python File
        run: wget https://github.com/manthankumar12/mlops_demo/blob/main/output.py -O python_file.py

      - name: Install Snowpark Dependencies
        run: |
          curl -Lo /tmp/snowpark.jar https://repo1.maven.org/maven2/net/snowflake/snowpark_2.12/0.10.1/snowpark_2.12-0.10.1.jar
          curl -Lo /tmp/snowpark-assembly.jar https://repo1.maven.org/maven2/net/snowflake/snowpark-sql_2.12/0.10.1/snowpark-sql_2.12-0.10.1-assembly.jar

      - name: Set up Snowflake Credentials
        run: |
          echo "export SNOWFLAKE_ACCOUNT='ls31517.ap-southeast-1'" >> $GITHUB_ENV
          echo "export SNOWFLAKE_USER='manthan'" >> $GITHUB_ENV
          echo "export SNOWFLAKE_PASSWORD='Manthanrana123'" >> $GITHUB_ENV
          echo "export SNOWFLAKE_WAREHOUSE='COMPUTE_WH'" >> $GITHUB_ENV
          echo "export SNOWFLAKE_DATABASE='SNOWLENS'" >> $GITHUB_ENV
          echo "export SNOWFLAKE_SCHEMA='DEMO'" >> $GITHUB_ENV
          echo "export SNOWFLAKE_ROLE='ACCOUNTADMIN'" >> $GITHUB_ENV

      - name: Deploy Python File to Snowflake
        run: |
          java -cp /tmp/snowpark.jar:/tmp/snowpark-assembly.jar com.snowflake.snowpark.SnowparkScriptRunner https://github.com/manthankumar12/mlops_demo/blob/main/output.py
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
